## Tutorial-1: Introduction to Pandas

In [35]:
import pandas as pd

In [36]:
df = pd.read_csv("ipl_dataset.csv")

In [37]:
df

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [38]:
df.shape

(816, 17)

In [39]:
df.head(2)

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    object
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: float64(1), int64(2), object(14)
memory usage: 108.5+ KB

In [41]:
df.columns

Index(['id', 'city', 'date', 'player_of_match', 'venue', 'neutral_venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result',
       'result_margin', 'eliminator', 'method', 'umpire1', 'umpire2'],
      dtype='object')

## Tutorial-2: Selecting rows and columns from dataframes

In [42]:
df.head(3)

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar

In [43]:
df.tail()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [44]:
df["player_of_match"]

0         BB McCullum
1          MEK Hussey
2         MF Maharoof
3          MV Boucher
4           DJ Hussey
            ...
811    AB de Villiers
812         JJ Bumrah
813     KS Williamson
814        MP Stoinis
815          TA Boult
Name: player_of_match, Length: 816, dtype: object

In [45]:
df[["player_of_match", "team1", "team2"]]

    player_of_match                        team1                        team2
0       BB McCullum  Royal Challengers Bangalore        Kolkata Knight Riders
1        MEK Hussey              Kings XI Punjab          Chennai Super Kings
2       MF Maharoof             Delhi Daredevils             Rajasthan Royals
3        MV Boucher               Mumbai Indians  Royal Challengers Bangalore
4         DJ Hussey        Kolkata Knight Riders              Deccan Chargers
..              ...                          ...                          ...
811  AB de Villiers  Royal Challengers Bangalore               Mumbai Indians
812       JJ Bumrah               Mumbai Indians               Delhi Capitals
813   KS Williamson  Royal Challengers Bangalore          Sunrisers Hyderabad
814      MP Stoinis               Delhi Capitals          Sunrisers Hyderabad
815        TA Boult               Delhi Capitals               Mumbai Indians

[816 rows x 3 columns]

In [46]:
df.player_of_match

0         BB McCullum
1          MEK Hussey
2         MF Maharoof
3          MV Boucher
4           DJ Hussey
            ...
811    AB de Villiers
812         JJ Bumrah
813     KS Williamson
814        MP Stoinis
815          TA Boult
Name: player_of_match, Length: 816, dtype: object

In [47]:
type(df["player_of_match"])

pandas.core.series.Series

In [48]:
#iloc - allows to select rows and columns based on integer location

df.iloc[0]

id                                      335982
city                                 Bangalore
date                                2008-04-18
player_of_match                    BB McCullum
venue                    M Chinnaswamy Stadium
neutral_venue                                0
team1              Royal Challengers Bangalore
team2                    Kolkata Knight Riders
toss_winner        Royal Challengers Bangalore
toss_decision                            field
winner                   Kolkata Knight Riders
result                                    runs
result_margin                            140.0
eliminator                                   N
method                                     NaN
umpire1                              Asad Rauf
umpire2                            RE Koertzen
Name: 0, dtype: object

In [49]:
df.iloc[0, 0]

335982

In [50]:
df.iloc[[0,2,4,5]]

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
5,335987,Jaipur,2008-04-21,SR Watson,Sawai Mansingh Stadium,0,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,bat,Rajasthan Royals,wickets,6.0,N,NaN,Aleem Dar,RB Tiffin

In [51]:
df.iloc[[0,2,4,5], [0,1,3]]

       id       city player_of_match
0  335982  Bangalore     BB McCullum
2  335984      Delhi     MF Maharoof
4  335986    Kolkata       DJ Hussey
5  335987     Jaipur       SR Watson

In [52]:
df.iloc[0:5, 1:10]

,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision
0,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field
1,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat
2,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat
3,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat
4,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat

In [53]:
#loc - it allows us to select rows and columns based on the labels

In [54]:
df.head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

In [55]:
test_df = df.iloc[5:10]

In [56]:
test_df

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
5,335987,Jaipur,2008-04-21,SR Watson,Sawai Mansingh Stadium,0,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,bat,Rajasthan Royals,wickets,6.0,N,NaN,Aleem Dar,RB Tiffin
6,335988,Hyderabad,2008-04-22,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,Delhi Daredevils,wickets,9.0,N,NaN,IL Howell,AM Saheba
7,335989,Chennai,2008-04-23,ML Hayden,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings,runs,6.0,N,NaN,DJ Harper,GA Pratapkumar
8,335990,Hyderabad,2008-04-24,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,3.0,N,NaN,Asad Rauf,MR Benson
9,335991,Chandigarh,2008-04-25,KC Sangakkara,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,Kings XI Punjab,runs,66.0,N,NaN,Aleem Dar,AM Saheba

In [57]:
test_df.iloc[0]

id                                 335987
city                               Jaipur
date                           2008-04-21
player_of_match                 SR Watson
venue              Sawai Mansingh Stadium
neutral_venue                           0
team1                    Rajasthan Royals
team2                     Kings XI Punjab
toss_winner               Kings XI Punjab
toss_decision                         bat
winner                   Rajasthan Royals
result                            wickets
result_margin                         6.0
eliminator                              N
method                                NaN
umpire1                         Aleem Dar
umpire2                         RB Tiffin
Name: 5, dtype: object

In [58]:
test_df.loc[5]

id                                 335987
city                               Jaipur
date                           2008-04-21
player_of_match                 SR Watson
venue              Sawai Mansingh Stadium
neutral_venue                           0
team1                    Rajasthan Royals
team2                     Kings XI Punjab
toss_winner               Kings XI Punjab
toss_decision                         bat
winner                   Rajasthan Royals
result                            wickets
result_margin                         6.0
eliminator                              N
method                                NaN
umpire1                         Aleem Dar
umpire2                         RB Tiffin
Name: 5, dtype: object

In [59]:
test_df.loc[5, "city"]

'Jaipur'

In [60]:
test_df.loc[[5,6,7], ["player_of_match", "team1", "team2"]]

  player_of_match                team1             team2
5       SR Watson     Rajasthan Royals   Kings XI Punjab
6        V Sehwag      Deccan Chargers  Delhi Daredevils
7       ML Hayden  Chennai Super Kings    Mumbai Indians

In [61]:
test_df.loc[5:9, "player_of_match":"winner"]

,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner
5,SR Watson,Sawai Mansingh Stadium,0,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,bat,Rajasthan Royals
6,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,Delhi Daredevils
7,ML Hayden,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings
8,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals
9,KC Sangakkara,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,Kings XI Punjab

## Tutorial-3: Filtering

In [63]:
df.head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

In [64]:
filter_1 = df["winner"] == "Chennai Super Kings"

In [65]:
type(filter_1)

pandas.core.series.Series

In [66]:
filter_1

0      False
1       True
2      False
3      False
4      False
       ...
811    False
812    False
813    False
814    False
815    False
Name: winner, Length: 816, dtype: bool

In [67]:
df[filter_1]

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
7,335989,Chennai,2008-04-23,ML Hayden,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings,runs,6.0,N,NaN,DJ Harper,GA Pratapkumar
11,335993,Chennai,2008-04-26,JDP Oram,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,bat,Chennai Super Kings,wickets,9.0,N,NaN,BF Bowden,AV Jayaprakash
14,335996,Bangalore,2008-04-28,MS Dhoni,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,13.0,N,NaN,BR Doctrove,RB Tiffin
27,336009,Delhi,2008-05-08,MS Dhoni,Feroz Shah Kotla,0,Delhi Daredevils,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,4.0,N,NaN,Aleem Dar,RB Tiffin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
770,1216506,Abu Dhabi,2020-11-01,RD Gaikwad,Sheikh Zayed Stadium,0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,9.0,N,NaN,PG Pathak,VK Sharma
777,1216513,Dubai,2020-10-04,SR Watson,Dubai International Cricket Stadium,0,Kings XI Punjab,Chennai Super Kings,Kings XI Punjab,bat,Chennai Super Kings,wickets,10.0,N,NaN,AY Dandekar,Nitin Menon
792,1216528,Dubai,2020-10-13,RA Jadeja,Dubai International Cricket Stadium,0,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings,bat,Chennai Super Kings,runs,20.0,N,NaN,AK Chaudhary,PR Reiffel
800,1216536,Dubai,2020-10-29,RD Gaikwad,Dubai International Cricket Stadium,0,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,6.0,N,NaN,C Shamshuddin,RK Illingworth
808,1216544,Dubai,2020-10-25,RD Gaikwad,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,bat,Chennai Super Kings,wickets,8.0,N,NaN,C Shamshuddin,RK Illingworth

In [68]:
df[df["winner"]=="Chennai Super Kings"]

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
7,335989,Chennai,2008-04-23,ML Hayden,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings,runs,6.0,N,NaN,DJ Harper,GA Pratapkumar
11,335993,Chennai,2008-04-26,JDP Oram,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,bat,Chennai Super Kings,wickets,9.0,N,NaN,BF Bowden,AV Jayaprakash
14,335996,Bangalore,2008-04-28,MS Dhoni,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,13.0,N,NaN,BR Doctrove,RB Tiffin
27,336009,Delhi,2008-05-08,MS Dhoni,Feroz Shah Kotla,0,Delhi Daredevils,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,4.0,N,NaN,Aleem Dar,RB Tiffin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
770,1216506,Abu Dhabi,2020-11-01,RD Gaikwad,Sheikh Zayed Stadium,0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,9.0,N,NaN,PG Pathak,VK Sharma
777,1216513,Dubai,2020-10-04,SR Watson,Dubai International Cricket Stadium,0,Kings XI Punjab,Chennai Super Kings,Kings XI Punjab,bat,Chennai Super Kings,wickets,10.0,N,NaN,AY Dandekar,Nitin Menon
792,1216528,Dubai,2020-10-13,RA Jadeja,Dubai International Cricket Stadium,0,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings,bat,Chennai Super Kings,runs,20.0,N,NaN,AK Chaudhary,PR Reiffel
800,1216536,Dubai,2020-10-29,RD Gaikwad,Dubai International Cricket Stadium,0,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,6.0,N,NaN,C Shamshuddin,RK Illingworth
808,1216544,Dubai,2020-10-25,RD Gaikwad,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,bat,Chennai Super Kings,wickets,8.0,N,NaN,C Shamshuddin,RK Illingworth

In [69]:
df.loc[filter_1]

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
7,335989,Chennai,2008-04-23,ML Hayden,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings,runs,6.0,N,NaN,DJ Harper,GA Pratapkumar
11,335993,Chennai,2008-04-26,JDP Oram,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,bat,Chennai Super Kings,wickets,9.0,N,NaN,BF Bowden,AV Jayaprakash
14,335996,Bangalore,2008-04-28,MS Dhoni,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,13.0,N,NaN,BR Doctrove,RB Tiffin
27,336009,Delhi,2008-05-08,MS Dhoni,Feroz Shah Kotla,0,Delhi Daredevils,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,4.0,N,NaN,Aleem Dar,RB Tiffin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
770,1216506,Abu Dhabi,2020-11-01,RD Gaikwad,Sheikh Zayed Stadium,0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,9.0,N,NaN,PG Pathak,VK Sharma
777,1216513,Dubai,2020-10-04,SR Watson,Dubai International Cricket Stadium,0,Kings XI Punjab,Chennai Super Kings,Kings XI Punjab,bat,Chennai Super Kings,wickets,10.0,N,NaN,AY Dandekar,Nitin Menon
792,1216528,Dubai,2020-10-13,RA Jadeja,Dubai International Cricket Stadium,0,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings,bat,Chennai Super Kings,runs,20.0,N,NaN,AK Chaudhary,PR Reiffel
800,1216536,Dubai,2020-10-29,RD Gaikwad,Dubai International Cricket Stadium,0,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,6.0,N,NaN,C Shamshuddin,RK Illingworth
808,1216544,Dubai,2020-10-25,RD Gaikwad,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,bat,Chennai Super Kings,wickets,8.0,N,NaN,C Shamshuddin,RK Illingworth

In [70]:
df.loc[filter_1, ["team1", "team2", "winner"]]

                           team1                  team2               winner
1                Kings XI Punjab    Chennai Super Kings  Chennai Super Kings
7            Chennai Super Kings         Mumbai Indians  Chennai Super Kings
11           Chennai Super Kings  Kolkata Knight Riders  Chennai Super Kings
14   Royal Challengers Bangalore    Chennai Super Kings  Chennai Super Kings
27              Delhi Daredevils    Chennai Super Kings  Chennai Super Kings
..                           ...                    ...                  ...
770              Kings XI Punjab    Chennai Super Kings  Chennai Super Kings
777              Kings XI Punjab    Chennai Super Kings  Chennai Super Kings
792          Chennai Super Kings    Sunrisers Hyderabad  Chennai Super Kings
800        Kolkata Knight Riders    Chennai Super Kings  Chennai Super Kings
808  Royal Challengers Bangalore    Chennai Super Kings  Chennai Super Kings

[106 rows x 3 columns]

In [ ]:
& and
| or

In [71]:
filter_2 = (df["winner"] == "Chennai Super Kings") & (df["city"] == "Chennai")

In [72]:
df.loc[filter_2, ["city", "team1", "team2", "winner"]]

,city,team1,team2,winner
7,Chennai,Chennai Super Kings,Mumbai Indians,Chennai Super Kings
11,Chennai,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings
31,Chennai,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings
142,Chennai,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings
146,Chennai,Chennai Super Kings,Rajasthan Royals,Chennai Super Kings
151,Chennai,Chennai Super Kings,Mumbai Indians,Chennai Super Kings
162,Chennai,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings
175,Chennai,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings
188,Chennai,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings
202,Chennai,Chennai Super Kings,Pune Warriors,Chennai Super Kings
212,Chennai,Chennai Super Kings,Deccan Chargers,Chennai Super Kings
216,Chennai,Chennai Super Kings,Rajasthan Royals,Chennai Super Kings
229,Chennai,Chennai Super Kings,Delhi Daredevils,Chennai Super Kings
237,Chennai,Chennai Super Kings,Kochi Tuskers Kerala,Chennai Super Kings
247,Chennai,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings
260,Chennai,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings
272,Chennai,Chennai Super Kings,Pune Warriors,Chennai Super Kings
274,Chennai,Chennai Super Kings,Rajasthan Royals,Chennai Super Kings
292,Chennai,Chennai Super Kings,Deccan Chargers,Chennai Super Kings
304,Chennai,Chennai Super Kings,Delhi Daredevils,Chennai Super Kings
320,Chennai,Delhi Daredevils,Chennai Super Kings,Chennai Super Kings
336,Chennai,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings
350,Chennai,Chennai Super Kings,Rajasthan Royals,Chennai Super Kings
354,Chennai,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings
358,Chennai,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings
365,Chennai,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings
386,Chennai,Chennai Super Kings,Delhi Daredevils,Chennai Super Kings
459,Chennai,Chennai Super Kings,Delhi Daredevils,Chennai Super Kings
461,Chennai,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings
482,Chennai,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings
487,Chennai,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings
494,Chennai,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings
503,Chennai,Chennai Super Kings,Rajasthan Royals,Chennai Super Kings
640,Chennai,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings
696,Chennai,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings
707,Chennai,Chennai Super Kings,Rajasthan Royals,Chennai Super Kings
713,Chennai,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings
718,Chennai,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings
736,Chennai,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings
745,Chennai,Chennai Super Kings,Delhi Capitals,Chennai Super Kings

In [73]:
filter_3 = (df["team1"] == "Mumbai Indians") | (df["team2"] == "Mumbai Indians")

In [74]:
df.loc[filter_3, ["team1", "team2"]]

                           team1                        team2
3                 Mumbai Indians  Royal Challengers Bangalore
7            Chennai Super Kings               Mumbai Indians
9                Kings XI Punjab               Mumbai Indians
12                Mumbai Indians              Deccan Chargers
15         Kolkata Knight Riders               Mumbai Indians
..                           ...                          ...
802               Mumbai Indians          Sunrisers Hyderabad
805               Mumbai Indians             Rajasthan Royals
811  Royal Challengers Bangalore               Mumbai Indians
812               Mumbai Indians               Delhi Capitals
815               Delhi Capitals               Mumbai Indians

[203 rows x 2 columns]

In [75]:
df.loc[~filter_3,  ["team1", "team2"]]

                           team1                  team2
0    Royal Challengers Bangalore  Kolkata Knight Riders
1                Kings XI Punjab    Chennai Super Kings
2               Delhi Daredevils       Rajasthan Royals
4          Kolkata Knight Riders        Deccan Chargers
5               Rajasthan Royals        Kings XI Punjab
..                           ...                    ...
808  Royal Challengers Bangalore    Chennai Super Kings
809          Sunrisers Hyderabad  Kolkata Knight Riders
810               Delhi Capitals        Kings XI Punjab
813  Royal Challengers Bangalore    Sunrisers Hyderabad
814               Delhi Capitals    Sunrisers Hyderabad

[613 rows x 2 columns]

In [76]:
filter_4 = (df["city"] =="Mumbai") | (df["city"] =="Delhi") | (df["city"] =="Chennai")

df.loc[filter_4]

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
7,335989,Chennai,2008-04-23,ML Hayden,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings,runs,6.0,N,NaN,DJ Harper,GA Pratapkumar
11,335993,Chennai,2008-04-26,JDP Oram,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,bat,Chennai Super Kings,wickets,9.0,N,NaN,BF Bowden,AV Jayaprakash
12,335994,Mumbai,2008-04-27,AC Gilchrist,Dr DY Patil Sports Academy,0,Mumbai Indians,Deccan Chargers,Deccan Chargers,field,Deccan Chargers,wickets,10.0,N,NaN,Asad Rauf,SL Shastri
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,1178425,Chennai,2019-05-01,MS Dhoni,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Delhi Capitals,Delhi Capitals,field,Chennai Super Kings,runs,80.0,N,NaN,AY Dandekar,Nitin Menon
746,1178426,Mumbai,2019-05-02,JJ Bumrah,Wankhede Stadium,0,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,Mumbai Indians,tie,NaN,Y,NaN,CK Nandan,S Ravi
748,1178428,Delhi,2019-05-04,A Mishra,Feroz Shah Kotla,0,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,bat,Delhi Capitals,wickets,5.0,N,NaN,AY Dandekar,IJ Gould
751,1178431,Mumbai,2019-05-05,HH Pandya,Wankhede Stadium,0,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians,field,Mumbai Indians,wickets,9.0,N,NaN,A Nand Kishore,CK Nandan
752,1181764,Chennai,2019-05-07,SA Yadav,"MA Chidambaram Stadium, Chepauk",0,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,bat,Mumbai Indians,wickets,6.0,N,NaN,NJ Llong,Nitin Menon

In [77]:
city = ["Mumbai", "Delhi", "Chennai"]

filter_5 = df["city"].isin(city)

In [78]:
df.loc[filter_5]

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
7,335989,Chennai,2008-04-23,ML Hayden,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings,runs,6.0,N,NaN,DJ Harper,GA Pratapkumar
11,335993,Chennai,2008-04-26,JDP Oram,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,bat,Chennai Super Kings,wickets,9.0,N,NaN,BF Bowden,AV Jayaprakash
12,335994,Mumbai,2008-04-27,AC Gilchrist,Dr DY Patil Sports Academy,0,Mumbai Indians,Deccan Chargers,Deccan Chargers,field,Deccan Chargers,wickets,10.0,N,NaN,Asad Rauf,SL Shastri
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,1178425,Chennai,2019-05-01,MS Dhoni,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Delhi Capitals,Delhi Capitals,field,Chennai Super Kings,runs,80.0,N,NaN,AY Dandekar,Nitin Menon
746,1178426,Mumbai,2019-05-02,JJ Bumrah,Wankhede Stadium,0,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,Mumbai Indians,tie,NaN,Y,NaN,CK Nandan,S Ravi
748,1178428,Delhi,2019-05-04,A Mishra,Feroz Shah Kotla,0,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,bat,Delhi Capitals,wickets,5.0,N,NaN,AY Dandekar,IJ Gould
751,1178431,Mumbai,2019-05-05,HH Pandya,Wankhede Stadium,0,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians,field,Mumbai Indians,wickets,9.0,N,NaN,A Nand Kishore,CK Nandan
752,1181764,Chennai,2019-05-07,SA Yadav,"MA Chidambaram Stadium, Chepauk",0,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,bat,Mumbai Indians,wickets,6.0,N,NaN,NJ Llong,Nitin Menon